# Generated by Django 5.0.1 on 2024-02-04 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('device_type', models.CharField(max_length=255)),
                ('device_model', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Assigned', 'Assigned'), ('Under repair', 'Under repair')], default='Available', max_length=50)),
                ('condition', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Device', to='Company.company')),
                ('current_assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_devices', to='Company.employee')),
            ],
        ),
        migrations.CreateModel(
            name='AssignDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('condition_before', models.TextField(blank=True, null=True)),
                ('condition_after', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='Company.employee')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='Device.device')),
            ],
        ),
    ]
