# Generated by Django 5.0.1 on 2024-02-05 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='condition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
