# Generated by Django 5.0.1 on 2024-02-05 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_company_user_employee_user'),
        ('Device', '0002_alter_device_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigndevice',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='Device.device'),
        ),
        migrations.AlterField(
            model_name='assigndevice',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='Company.employee'),
        ),
    ]
