# Generated by Django 5.0.1 on 2024-02-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0003_alter_assigndevice_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigndevice',
            name='id_checked_out',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
