# Generated by Django 5.0.1 on 2024-02-05 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0004_assigndevice_id_checked_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assigndevice',
            old_name='id_checked_out',
            new_name='is_checked_out',
        ),
    ]
