# Generated by Django 5.0.1 on 2024-02-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_company_user_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_email',
            field=models.EmailField(max_length=254),
        ),
    ]
